# ML Learning Project

### Task 1: Load the dataset

In [ ]:
import pandas as pd

In [83]:
df = pd.read_csv('./data/employee_attrition.csv')
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

### Task 2: Understand the Data

In [84]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB
None

In [ ]:
print(df.shape)

# 35 Columns
# 1470 Rows

In [ ]:
df.nunique()

### Task 2: Understand Data

In [ ]:
# null values
df.isnull().sum()

# There is no null data

In [ ]:
df.duplicated().sum()
# No duplicate data

In [ ]:
df.nunique().sort_values()

In [ ]:
df["JobRole"].value_counts()

In [ ]:
df["OverTime"].value_counts()

In [ ]:
# Important categorical distributions
df["Attrition"].value_counts()

In [ ]:
df['StandardHours']

In [ ]:
df.describe().T

### Task 3: EDA

In [ ]:
df['Attrition'].value_counts()

In [ ]:
df["Attrition"].value_counts(normalize=True) * 100

In [ ]:
import matplotlib.pyplot as plt

df["Age"].hist(bins=20)

plt.xlabel("Age")
plt.ylabel("Number of employees")
plt.title("Age Distribution")
plt.show()

In [ ]:

import matplotlib.pyplot as plt

df["MonthlyIncome"].hist()

plt.xlabel("MonthlyIncome")
plt.ylabel("Number of employees")
plt.title("Monthly Income of Distribution")
plt.show()


# Interpretation: It's traingle hierarchy, highly payed employees are most, than medium paying emp and at last highly paid employees
# Ranges from 2500 to 20000

In [ ]:

import matplotlib.pyplot as plt

df["YearsAtCompany"].hist()

plt.xlabel("YearsAtCompany")
plt.ylabel("Number of employees")
plt.title("Experience Distribution")
plt.show()

# most employees has lower experience
# very rare employees has high experince
# medium employees has middle experince

In [ ]:
df.groupby("Attrition")[["Age","MonthlyIncome","YearsAtCompany"]].mean()

### Task 3: Feature Engineerring

#### Remove unnecessary columns

In [ ]:
df.nunique().sort_values()

# Safe to remove columns:

    # EmployeeCount
    # Over18
    # StandardHours

# because model can't learn any meaningful thing from it

In [85]:
# Identify identifier column
# It also doesn't add anything meaningful
df['EmployeeNumber']

# Candidate to remove

0          1
1          2
2          4
3          5
4          7
        ...
1465    2061
1466    2062
1467    2064
1468    2065
1469    2068
Name: EmployeeNumber, Length: 1470, dtype: int64

In [86]:
df[
    [
        "YearsAtCompany",
        "YearsInCurrentRole",
        "YearsSinceLastPromotion",
        "YearsWithCurrManager"
    ]
].describe()

,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000
mean,7.008163,4.229252,2.187755,4.123129
std,6.126525,3.623137,3.222430,3.568136
min,0.000000,0.000000,0.000000,0.000000
25%,3.000000,2.000000,0.000000,2.000000
50%,5.000000,3.000000,1.000000,3.000000
75%,9.000000,7.000000,3.000000,7.000000
max,40.000000,18.000000,15.000000,17.000000

In [87]:
df["RoleTenureRatio"] = (
    df["YearsInCurrentRole"] /
    df["YearsAtCompany"].replace(0, 1)
)

In [91]:
# removing the unnecessary columns
columns_to_remove = [
    "EmployeeNumber",
    "EmployeeCount",
    "StandardHours",
    "Over18"
]

df = df.drop(columns=columns_to_remove)

df.shape

(1470, 32)